team10/knu_reminder/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
]

team10/main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDV.as_view(), name='post_detail'),
    path('popup/', views.PopupView.as_view(), name='popup'),
    path('kakao_redirect/', views.KakaoLoginView.as_view(), name='kakao_redirect'),
    path('kakao_delete/', views.KakaoDeleteView, name='delete'),
    path('kakao_logout/', views.KakaoLogoutView, name='logout'),
    path('create_board/', views.CreateBoardView, name='create_board'),
    path('delete_board/', views.DeleteBoardView, name='board_delete'),
    path('bookmark/', views.BookmarkView, name='bookmark'),
    path('alarm/', views.AlarmView, name='alarm'),
    path('share/', views.ShareView, name='share'),
]

team10/main/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractBaseUser

# Create your models here.

class MajorList(models.Model):
    major = models.CharField(max_length=20, default=0)

    class Meta:
        db_table = "major_list"

class User(AbstractBaseUser):
    social = models.CharField(max_length=20, blank=True)
    social_login_id = models.CharField(max_length=50, blank=True)
    token = models.TextField('Token', null=True)
    refresh_token = models.TextField('Refresh_token', null=True)
    nickname = models.CharField(max_length=20, blank=True)

    USERNAME_FIELD = 'id'
    REQUIRED_FIELDS = ['social', 'social_login_id']

class Bookmark(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    post = models.TextField('Posts', null=True)
    alarm = models.BooleanField(default=False)

class BoardList(models.Model):
    board_name = models.CharField(verbose_name='NAME', max_length=50, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    department = models.TextField('Department', null=True)
    alarm = models.BooleanField(default=False)
    
class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=100)
    slug = models.SlugField('SLUG', allow_unicode=True,
                            help_text='calender short title')
    content = models.TextField('Content', blank=True)
    upload_dt = models.DateTimeField('Upload Date')
    department = models.CharField('Department', max_length=50)
    url = models.URLField('URL')

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'main_post'
        ordering = ('-upload_dt', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:post_detail', args=(self.id, ))

    def get_previous(self):
        return self.get_previous_by_upload_dt()

    def get_next(self):
        return self.get_next_by_upload_dt()

team10/main/views.py
import json
import jwt
import requests
from django.views import View
from django.http import JsonResponse, HttpResponse
from django.contrib import auth
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, TemplateView
from main.models import Post, User, MajorList, BoardList, Bookmark
from knu_reminder import secret
from django.db.models import Q

# Create your views here.

def AlarmView(request):
    board_name = request.POST.get('board_name', None)
    if board_name == "bookmark":
        bookmark = Bookmark.objects.get(user=request.user)
        if bookmark.alarm:
            bookmark.alarm = False
            result = False
        else:
            bookmark.alarm = True
            result = True
        bookmark.save()
    else:
        board = BoardList.objects.get(user=request.user, board_name=board_name)
        if board.alarm:
            board.alarm = False
            result = False
        else:
            board.alarm = True
            result = True
        board.save()
    context = {'result':result}
    return HttpResponse(json.dumps(context), content_type="application/json")
    

def BookmarkView(request):
    pk = str(request.POST.get('pk', None))
    bookmark = Bookmark.objects.get(user=request.user)
    jsonDec = json.decoder.JSONDecoder()

    try:
        ids = jsonDec.decode(bookmark.post)
        if pk not in ids:
            ids.append(pk)
            message = "북마크 완료"
            result = True
        else:
            ids.remove(pk)
            message = "북마크 삭제 완료"
            result = False
        bookmark.post = json.dumps(ids)
        bookmark.save()
    except:
        ids = []
        ids.append(pk)
        bookmark.post = json.dumps(ids)
        message = "북마크 완료"
        bookmark.save()
        result = True

    context = {'message': message, 'result':result}
    return HttpResponse(json.dumps(context), content_type="application/json")

def DeleteBoardView(request):
    BoardList.objects.get(board_name=request.GET['board_name'], user=request.user).delete()
    return redirect('main:home')

def CreateBoardView(request):
    try: 
        BoardList.objects.get(board_name=request.POST['board_name'])
        return redirect('main:popup')
    except:
        BoardList(board_name=request.POST['board_name'], department=json.dumps(request.POST.getlist('department[]')), user=request.user).save()
        return HttpResponse('<script type="text/javascript">window.close()</script>')  

def ShareView(request):
    id = request.POST.get('pk', None)
    post = Post.objects.get(id=id)
    ACCESS_TOKEN = request.user.token

    '''
    url = 'https://kapi.kakao.com/v1/api/talk/friends'
    headers = {
        "Authorization": f"Bearer {ACCESS_TOKEN}"
    }
    response = requests.get(url, headers=headers)
    if response.status_code == 403:
        required_scopes = json.loads(response.text).get('required_scopes')
        url = f'https://kauth.kakao.com/oauth/authorize?client_id={secret.App_key}&redirect_uri={secret.Redirect_URI}&response_type=code&scope={",".join(str(x) for x in required_scopes)}'
        requests.get(url)

        url = 'https://kapi.kakao.com/v1/api/talk/friends'
        headers = {
            "Authorization": f"Bearer {ACCESS_TOKEN}"
        }
        response = requests.get(url, headers=headers)

    
    print(response)
    '''
    
    url = 'https://kapi.kakao.com/v2/api/talk/memo/default/send'
    headers = {
        "Authorization": f"Bearer {ACCESS_TOKEN}"
    }
    body = {
        'template_object' : json.dumps({ 
            "object_type" : "text",
            "text" : f"{post.title}",
            "link" : {
                "web_url" : f"{post.url}",
                "mobile_web_url" : f"{post.url}",
            }
        })
    }
    response = requests.post(url, headers=headers, data=body)
    
    context = {'success':response.status_code}

    return HttpResponse(json.dumps(context), content_type="application/json")

def KakaoDeleteView(request):
    user = User.objects.get(id=request.user.id)
    user.delete()
    return redirect('main:home')

def KakaoLogoutView(request):
    auth.logout(request)
    print("logout")
    return redirect('main:home')

class KakaoLoginView(View):
    def get(self, request):
        kakao_access_code = request.GET.get('code', None)
        url = 'https://kauth.kakao.com/oauth/token'
        headers = {'Content-type' : 'application/x-www-form-urlencoded; charset=utf-8'}
        body = {'grant_type' : 'authorization_code',
                'client_id' : secret.App_key,
                'redirect_uri' : secret.Redirect_URI,
                'code': kakao_access_code }
        
        token_kakao_response = requests.post(url, headers=headers, data=body)
        access_token = json.loads(token_kakao_response.text).get('access_token')
        refresh_token = json.loads(token_kakao_response.text).get('refresh_token')

        url = 'https://kapi.kakao.com/v2/user/me'
        headers = {
            'Authorization' : f'Bearer {access_token}',
            'Content-type' : 'application/x-www-form-urlencoded; charset=utf-8'
        }
        kakao_response = requests.get(url, headers=headers)
        kakao_response = json.loads(kakao_response.text)

        nickname = kakao_response['properties']['nickname']

        if User.objects.filter(social_login_id = kakao_response['id']).exists():
            user = User.objects.get(social_login_id=kakao_response['id'])
            user.token = access_token
            user.refresh_token = refresh_token
            user.save()
            # jwt_token = jwt.encode({'id':user.id}, secret.SECRET_KEY, algorithm='HS256').decode('utf-8')
            auth.login(request,user)

            return redirect('main:home')
        User(
            social_login_id = kakao_response['id'],
            social = 'kakao',
            token = access_token,
            refresh_token= refresh_token,
            nickname= nickname,
        ).save()
        user = User.objects.get(social_login_id=kakao_response['id'])
        Bookmark(
            user=user
        ).save()
        auth.login(request, user)
        
        return redirect('main:home')

class PopupView(TemplateView):
    template_name = 'main/home_popup.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        major_list = MajorList.objects.all()
        context['departments'] = major_list
        return context

class HomeView(TemplateView):
    template_name = 'main/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['app_key'] = secret.App_key
        context['redirect_uri'] = secret.Redirect_URI

        if self.request.user.is_authenticated:
            boards = BoardList.objects.filter(user=self.request.user)
            bookmark = Bookmark.objects.get(user=self.request.user)
            bookmark = bookmark.alarm
        else:
            boards = []
            bookmark = False
        context['boards'] = boards
        context['bookmark'] = bookmark

        return context

class PostLV(ListView):
    template_name = 'main/post_list.html'
    model = Post
    paginate_by = 20

    def get_queryset(self):
        if self.request.GET['board_name'] == "Bookmark":
            bookmark = Bookmark.objects.get(user=self.request.user)
            jsonDec = json.decoder.JSONDecoder()
            try:
                ids = jsonDec.decode(bookmark.post)
            except:
                ids = []
            try:
                search_key = self.request.GET['search_key']
                return Post.objects.filter(Q(title__icontains=search_key) & Q(id__in=ids))
            except:
                return Post.objects.filter(id__in=ids)
        else:
            try:
                board = BoardList.objects.get(user=self.request.user, board_name=self.request.GET['board_name'])
                jsonDec = json.decoder.JSONDecoder()
                departments = jsonDec.decode(board.department)
                try:
                    search_key = self.request.GET['search_key']
                    return Post.objects.filter(Q(title__icontains=search_key) & Q(department__in=departments))
                except:
                    return Post.objects.filter(department__in=departments)
            except: # 전체 공지
                try:
                    search_key = self.request.GET['search_key']
                    return Post.objects.filter(title__icontains=search_key)
                except:
                    return Post.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.GET['board_name'] == "Bookmark":
            context['board_name'] = 'Bookmark'
            return context
        else:
            try:
                board = BoardList.objects.get(user=self.request.user, board_name=self.request.GET['board_name'])
                jsonDec = json.decoder.JSONDecoder()
                departments = jsonDec.decode(board.department)
                context['departments'] = departments
                context['board_name'] = board.board_name
                return context
            except:
                context['board_name'] = "전체 공지"
                return context

class PostDV(DetailView):
    template_name = 'main/post_detail.html'
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        bookmark = Bookmark.objects.get(user=self.request.user)
        jsonDec = json.decoder.JSONDecoder()
        try:
            ids = jsonDec.decode(bookmark.post)
        except:
            ids = []

        if str(kwargs['object'].id) in ids:
            context['is_bookmark'] = True
        else:
            context['is_bookmark'] = False
        try:
            context['board_name'] = self.request.GET['board_name']
            return context

team10/main/templates/main/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>학과공지 알리미</title>
    <link rel = "stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel = "stylesheet" href="{% static 'css/site.css' %}">
    <link rel="shortcut icon" href="http://www.knu.ac.kr/wbbs/img/favicon.ico"/>
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
    />
    <script
    src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    <style>
        h1{
            font-size: 70px;
            text-align: center;
        }        
        a {
            color: black;
            text-decoration: none;
        }
    </style>
    <script language = "javascript">
        function showPopup() {
            window.open("{% url 'main:popup' %}", "게시판 추가", "width = 500, height = 800, left = 700, top = 100");
        }
    </script>
    <script type="text/javascript">
        $(document).on("click", ".alarm", function(){
          var board_name = $(this).attr('name')
          var id = $(this).attr('id')
          $.ajax({ 
            type: "POST",
            url: "{% url 'main:alarm' %}",
            data: {'board_name': board_name, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, // 서버로 데이터 전송시 옵션
            dataType: "json", 
            // 서버측에서 전송한 Response 데이터 형식 (json)
            success: function(response){ // 통신 성공시 - 알람 버튼 칠하기
              if (response.result) { // 알람 설정 완료
                $(`#${id}`).children("#alarm_icon").replaceWith( '<i class="fas fa-bell" id="alarm_icon"></i>' );
              }
              else {
                $(`#${id}`).children("#alarm_icon").replaceWith( '<i class="far fa-bell" id="alarm_icon"></i>' )
              }
              
            },
            error: function(request, status, error){ // 통신 실패시 - alert
              alert("북마크 실패하였습니다.")
            },
          });
        })
      </script>
</head>
<body>
    <br>
    <h1>
        <img src = "{% static 'image/knu_image.jpg' %}" width = "150" height = "50">
        학과공지 알리미
    </h1>

    <br><br>
    <div class = "container">
        {% if not user.is_authenticated %}
            <div style="float: right;">
                <a href="https://kauth.kakao.com/oauth/authorize?client_id={{ app_key }}&redirect_uri={{ redirect_uri }}&response_type=code">
                    <img src = "{% static 'image/kakao_login.png' %}">
                </a>
            </div>
        {% else %}
            <div style="float: left;">
                <a href="{% url 'main:logout' %}"><input class="btn btn-outline-secondary" style="width:25%" value="로그아웃"></a>
                <a href="{% url 'main:delete' %}"><input class="btn btn-outline-secondary" style="width:25%" value="회원탈퇴"></a>
            </div>
        {% endif %}
        <!--검색창-->
        {% if user.is_authenticated %}
            <div style="float: right;">
                <form class="navbar-search pull-right" action="{% url 'main:post_list' %}" method='GET'>
                    <input class="search-query" type="text" placeholder="Search" name='search_key'>
                    <input class="btn btn-secondary" type="submit" value="검색">
                    <input type="text" value="전체 공지" name='board_name' style="display: none">
                </form>
            </div>
        {% endif %}

        <!--전체게시판-->
        <br><br>
        <table class = "table table-hover">
            <thead>
                <tr>
                    <th>전체 게시판</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><a href="{% url 'main:post_list' %}?board_name=전체 공지">전체 공지사항</a></td>
                    <td></td>
                    <td></td>
                </tr>
                {% if user.is_authenticated %}
                    <tr>
                        <td><a href="{% url 'main:post_list' %}?board_name=Bookmark">북마크 공지사항</a></td>
                        <td>
                            <button type="button" class="alarm" name='bookmark' id="bookmark">
                                {% if bookmark %}
                                    <i class="fas fa-bell" id="alarm_icon"></i>
                                {% else %}
                                    <i class="far fa-bell" id="alarm_icon"></i>
                                {% endif %}
                            </button>
                        </td>
                        <td></td>
                    </tr>
                    {% for board in boards %}
                        <tr>
                            <td><a href="{% url 'main:post_list' %}?board_name={{ board.board_name }}">{{ board.board_name }}</a></td>
                            <td style="width:1cm;">
                                <button type="button" class="alarm" name='{{ board.board_name }}' id="{{ board.id }}">
                                    {% if board.alarm %}
                                        <i class="fas fa-bell" id="alarm_icon"></i>
                                    {% else %}
                                        <i class="far fa-bell" id="alarm_icon"></i>
                                    {% endif %}
                                </button>
                            </td>
                            <td style="width:3.1cm;">
                                <a href="{% url 'main:board_delete' %}?board_name={{ board.board_name }}">
                                    <input class="btn btn-outline-secondary" style="width:115%" value="게시판삭제" ></a>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>

        <!--게시판추가 버튼-->
        {% if user.is_authenticated %}
            <div style = "float: right;">
                <button type = "button" onclick= "showPopup();" class = "btn btn-secondary">게시판추가</button>
            </div>
        {% endif %}
    </div>
</body>
</html>

team10/main/templates/main/home_popup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시판 추가</title>
    <link rel = "stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel = "stylesheet" href="{% static 'css/site.css' %}">
    <link rel="shortcut icon" href="http://www.knu.ac.kr/wbbs/img/favicon.ico"/>
    <script language = "javascript">
        function closePopup() {
            close();
        }
    </script>
</head>
<body>
    <div class = "container">
        <table class = "table table-striped">
            <thead> 
                <tr> 
                    <th>게시판 리스트</th>
                    <th>추가</th>
                </tr>
            </thead> 
            <tbody> 
                <form method="post" action="{% url 'main:create_board' %}">
                    {% csrf_token %}
                    {% for department in departments %}
                    <tr> 
                        <td>{{ department.major }}</td>
                        <td>
                            <div class="custom-control custom-switch">
                                <input type="checkbox" name="department[]" value="{{ department.major }}" class="custom-control-input" id="{{ department.major }}">
                                <label class="custom-control-label" for="{{ department.major }}"></label>
                            </div>
                        </td>> 
                    </tr> 
                    {% endfor %}
                    <div style="float: right;">
                        <input type="text" name="board_name" placeholder="게시판 이름" size="20" required>
                        <input type="submit" value="게시판 생성" class="btn btn-secondary">
                    </div>
                </form>
            </tbody>     
        </table>
    </div>
</body>
</html>

team10/main/templates/main/post_detail.html
{% load static %}
{% load social_share %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>학과공지 알리미</title>
    <link rel = "stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel = "stylesheet" href="{% static 'css/site.css' %}">
    <link rel="shortcut icon" href="http://www.knu.ac.kr/wbbs/img/favicon.ico"/>
    <style>
        h1{
            font-size: 70px;
            text-align: center;
        }
        th {
            border-top: 2px solid;
            border-bottom: 0.5px solid;
            padding: 10px 5px;
            border-color: gray;
            width: 1400px;
            background-color: rgb(206, 206, 206);
        }
        td {
            border-bottom: 1px solid;
            padding: 10px 5px;
            border-color: gray;
            width: 1400px;
        }
    </style> 
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
    />
    <script
    src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    <script type="text/javascript">
      $(document).on("click", ".bookmark", function(){
        var pk = $(this).attr('name')
        $.ajax({ 
          type: "POST",
          url: "{% url 'main:bookmark' %}",
          data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, // 서버로 데이터 전송시 옵션
          dataType: "json", 
          // 서버측에서 전송한 Response 데이터 형식 (json)
          success: function(response){ // 통신 성공시 - 북마크 버튼 칠하기
            if (response.result) {
                $('#bookmark').replaceWith( '<i class="fas fa-bookmark" id="bookmark"></i>' );
            }
            else {
                $('#bookmark').replaceWith( '<i class="far fa-bookmark" id="bookmark"></i>' )
            }
            
          },
          error: function(request, status, error){ // 통신 실패시 - alert
            alert("북마크 실패하였습니다.")
          },
        });
      })
      $(document).on("click", "#share", function() {
          var pk = $(this).attr('name')
          $.ajax({
            type: "POST",
            url: "{% url 'main:share' %}",
            data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, // 서버로 데이터 전송시 옵션
            dataType: "json", 
            success: function(response) {
                switch(response.success) {
                    case 200: 
                        alert("나에게 카카오톡 전송 완료하였습니다!");
                        break;
                    case 403:
                        alert("메세지 접근 권한 없음");
                        break;
                }
            },
            error: function(request, status, error) {
                alert("kakao API fail")
            },
          });
      })
    </script>
</head>

<body>
    <!--학과이름-->
    <br>
    <h1>
        <a href="{% url 'main:post_list' %}{% if board_name %}?board_name={{ board_name }}{% endif %}">
            <img src = "{% static 'image/knu_image.jpg' %}" width = "150" height = "50">
            {{ board_name }}
        </a>
    </h1>   
    <div class = "container">
        <button type="button" class="btn btn-light">
            {% post_to_facebook post.get_absolute_url "Facebook" %}
        </button>
        <button type="button" class="btn btn-light">
            {% post_to_twitter post.get_absolute_url "Twitter" %}
        </button>
        <button type="button" class="btn btn-light" id="share" name='{{ post.id }}'>
            카카오톡 공유
        </button>
        <button type="button" class="bookmark" name='{{ post.id }}'>
            {% if is_bookmark %}
                <i class="fas fa-bookmark" id="bookmark"></i>
            {% else %}
                <i class="far fa-bookmark" id="bookmark"></i>
            {% endif %}
        </button>        
    </div>
    <br><br>
    <div class = "container">
        <!--게시글-->
        <table>
            <tr>
                <th>{{ post.title }}</th>
            </tr>
            <tr>
                <td>작성일 {{ post.upload_dt }}</td>
            </tr>
            <tr>
                <td>{{ post.content|linebreaks }}</td>
            </tr>
        </table>
        
        <!--이전/다음글 버튼-->
        <br>
        <div class = "row text-center">
            <div class= "col">
                <button type="button" class="btn btn-outline-secondary"><a href="{{ post.get_previous.get_absolute_url }}{% if board_name %}?board_name={{ board_name }}{% endif %}">이전글</a></button>
                <button type="button" class="btn btn-outline-secondary"><a href="{% url 'main:post_list' %}{% if board_name %}?board_name={{ board_name }}{% endif %}">목록</a></button>
                <button type="button" class="btn btn-outline-secondary"><a href="{{ post.get_next.get_absolute_url }}{% if board_name %}?board_name={{ board_name }}{% endif %}">다음글</a></button>
            </div>    
        </div>
    </div>
        
    <script src = "http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type = "text/javascript" src = "{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

team10/main/templates/main/post_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>학과공지 알리미</title>
    <link rel = "stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel = "stylesheet" href="{% static 'css/site.css' %}">
    <link rel="shortcut icon" href="http://www.knu.ac.kr/wbbs/img/favicon.ico"/>
    <style>
        h1{
            font-size: 70px;
            text-align: center;
        }
    </style>

</head>
<body>
    <br>
    <h1>
        <a href="{% url 'main:home' %}">
            <img src = "{% static 'image/knu_image.jpg' %}" width = "150" height = "50">
            {{ board_name }}
        </a>
    </h1>
    <p class="text-center">
        {% for department in departments %}
            {{ department }}
        {% endfor %}
    </p>

    <br><br>
    <div class = "container">
        <!--검색창-->
        <div style="float: right;">
            <form class="navbar-search pull-right" action="" method='GET'>
                <input class="search-query" type="text" placeholder="Search" name='search_key'>
                <input type="text" name="board_name" value='{{ board_name }}' style="display:none">
                <input class="btn btn-secondary" type="submit" value="검색">
            </form>
        </div>


        <!--공지리스트-->
        <table class = "table table-striped">
            <thead> 
                <tr> 
                    <th width = "30">번호</th> 
                    <th width = "350">제목</th> 
                    <th width = "130">등록일</th> 
                </tr> 
            </thead> 
            <tbody> 
                {% for post in object_list %}
                <tr> 
                    <td class = "text-center">{{ forloop.revcounter }}</td> 
                    <td><a href="{% url 'main:post_detail' post.id %}{% if board_name %}?board_name={{ board_name }}{% endif %}">{{ post.title }}</a></td> 
                    <td class = "text-center">{{ post.upload_dt }}</td> 
                </tr> 
                {% endfor %} 
            </tbody>     
        </table>    

        <!--페이지번호-->
        <div class = "text-center">
            <ul class = "pagination justify-content-center">
                {% if page_obj.has_previous %}
                    {% if page_obj.previous_page_number > 1 %}
                        <li class = "page-item"><a class="page-link" href="?page=1{% if board_name %}&board_name={{ board_name }}{% endif %}">맨 앞으로</a></li>
                    {% endif %}
                    {% if page_obj.number|add:-10 > 1 %}
                        <li class = "page-item"><a class="page-link" href="?page={{ page_obj.number|add:-10 }}{% if board_name %}&board_name={{ board_name }}{% endif %}">{{ page_obj.number|add:-10 }}</a></li>
                        <li class = "page-item"><a class="page-link" href="#">...</a></li>
                    {% endif %}
                    <li class = "page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if board_name %}&board_name={{ board_name }}{% endif %}">{{ page_obj.previous_page_number }}</a></li>
                {% endif %}
                <li class = "page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                    <li class = "page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% if board_name %}&board_name={{ board_name }}{% endif %}">{{ page_obj.next_page_number }}</a></li>
                    <li class = "page-item"><a class="page-link" href="#">...</a></li>
                    {% if page_obj.number|add:10 < page_obj.paginator.num_pages %}
                        <li class = "page-item"><a class="page-link" href="?page={{ page_obj.number|add:10 }}{% if board_name %}&board_name={{ board_name }}{% endif %}">{{ page_obj.number|add:10 }}</a></li>
                    {% endif %}
                    <li class = "page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if board_name %}&board_name={{ board_name }}{% endif %}">맨 뒤로</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    
    <script src = "http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type = "text/javascript" src = "{% static 'js/bootstrap.js' %}"></script>
</body>
</html>